# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   # - ../base/facebooc
#   - ../base/instavote
# # patchesStrategicMerge:
# #   # - facebooc-deploy-kustomization.yaml
# #   - vote-deploy-kustomization.yaml
 
#  patches:
#   - path: vote-deploy-kustomization.yaml
#     target:
#       kind: Kustomization
#       name: vote
#       namespace: instavote


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/instavote
patches:
  - path: vote-deploy-kustomization.yaml
    target:
      kind: Kustomization
      name: vote
      namespace: instavote
