apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vote
  namespace: instavote
spec:
  interval: 1m0s
  path: ./kustomize/vote/staging         # ✅ Precise path
  prune: true
  sourceRef:
    kind: GitRepository
    name: vote
  targetNamespace: instavote
  healthChecks:
    - kind: Deployment
      name: vote
  timeout: 3m0s
