apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vote
  namespace: instavote
spec:
  interval: 1m0s
  path: ./kustomize/vote/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: vote
  targetNamespace: instavote
  healthChecks:
    - apiVersion: apps/v1         # ✅ Add this
      kind: Deployment
      name: vote
      namespace: instavote        # ✅ Explicitly set namespace
  timeout: 3m0s
