apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vote
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kustomize/instavote/staging  # ✅ matches actual manifests
  prune: true
  serviceAccountName: instavote
  targetNamespace: instavote
  sourceRef:
    kind: GitRepository
    name: vote
    namespace: flux-system
  healthChecks:
    - kind: Deployment
      name: vote
      namespace: instavote
  timeout: 3m0s
